apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: jenkins
  namespace: immediate
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-central1-a
#  fsType: "ext4" 
